language: node_js
node_js:
    - "10"
cache: yarn
# before_install:
    # - sudo apt-get -y --no-install-recommends install texlive-full # 更新系统字体列表
install:
    - yarn
script:
    - yarn build 
    # && yarn export
after_success:
    - git config --global user.name "${USERNAME}"
    - git config --global user.email "${EMAIL}"
    # - git checkout ${PDF_BRANCH}
    # - git add -A
    # - git commit -m '[skip ci] deploy pdf profile' # export PDF in travis has a bug
    # - git push "https://${GH_TOKEN}@${REPO}" ${PDF_BRANCH}:${PDF_BRANCH}
    - cd docs/.vuepress/dist
    - git init
    - git checkout ${WEB_BRANCH}
    - git add -A
    - git commit -m 'deploy web profile'
    - git push --force "https://${GH_TOKEN}@${REPO}" ${WEB_BRANCH}:${WEB_BRANCH}
